pipeline {
    agent none
    stages {
        stage('Build Docker Image') {
            agent {
                label 'built-in'
            }
            steps {
                checkout scm
                sh 'docker build -t my-python-agent:latest .'
            }
        }
        stage('Checkout') {
            agent {
                label 'custom-docker-agent'
            }
            steps {
                checkout scm
            }
        }
        stage('Build') {
            agent {
                label 'custom-docker-agent'
            }
            steps {
                sh 'python --version'
            }
        }
        stage('Test') {
            agent {
                label 'custom-docker-agent'
            }
            steps {
                sh 'pytest tests/'
            }
        }
    }
    post {
        always {
            node('built-in') {
                cleanWs()
            }
        }
    }
}
