pipeline {
    agent none  // No agent is used in the pipeline
    stages {
        stage('Build Docker Image') {
            steps {
                node('built-in') {  // or 'any' if you want to use any available agent
                    // Build the Docker image and tag it with 'latest'
                    sh 'docker build -t my-python-agent:latest .'
                }
            }
        }
    }
}
