pipeline {
    agent none

    stages {
        stage('Build Docker Image') {
            agent { label 'any' }  // Assign an agent for this specific stage
            steps {
                // Build the Docker image and tag it with 'latest'
                sh 'docker build -t my-python-agent:latest .'
            }
        }
    }
}
